name: Article Deployment
on:
  [push]
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3 Bucket
        run: aws s3 sync ./public s3://kocoblo.com

      - name: Invalidate Cloudfront CDN
        run: aws cloudfront create-invalidation --distribution-id=${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'

      - name: Invalidate Cloudfront CDN (www)
        run: aws cloudfront create-invalidation --distribution-id=${{ secrets.WWW_CLOUDFRONT_DISTRIBUTION_ID }} --paths '/*'
