name: Docker Deployment
on:
  [push]
  # schedule:
  #   - cron: "0 0 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Authorize ECR
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 776733965771.dkr.ecr.us-east-1.amazonaws.com

      - name: Move to Form
        run: cd api/form

      - name: Build Image
        run: docker build --build-arg SENDGRID_API_KEY="${{ secrets.SENDGRID_API_KEY }}" --build-arg SENDGRID_AUTHORIZED_EMAIL="${{ secrets.SENDGRID_AUTHORIZED_EMAIL }}" -t kocoblo/form .

      - name: Tag Image
        run: docker tag kocoblo/form:latest 776733965771.dkr.ecr.us-east-1.amazonaws.com/kocoblo/form:latest

      - name: Push Image
        run: docker push 776733965771.dkr.ecr.us-east-1.amazonaws.com/kocoblo/form:latest
