name: S3 Deployment

on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - uses: actions/checkout@v2

      - name: Show Secrets
        run: echo ${{ secrets.GATSBY_ALGOLIA_APP_ID }}

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Deploy
        run: yarn deploy

      # - name: Deploy
      #   uses: reggionick/s3-deploy@v3
      #   with:
      #     folder: build
      #     bucket: ${{ secrets.S3_BUCKET }}
      #     bucket-region: ${{ secrets.S3_BUCKET_REGION }}
      #     dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      #     invalidation: /
      #     delete-removed: true
      #     no-cache: true
      #     private: true

env:
  GATSBY_ALGOLIA_APP_ID: ${{ secrets.GATSBY_ALGOLIA_APP_ID }}
  GATSBY_ALGOLIA_ADMIN_API_KEY: ${{ secrets.GATSBY_ALGOLIA_ADMIN_API_KEY }}
  GATSBY_ALGOLIA_SEARCH_API_KEY: ${{ secrets.GATSBY_ALGOLIA_SEARCH_API_KEY }}
  PRISMIC_API_KEY: ${{ secrets.PRISMIC_API_KEY }}
